openapi: 3.0.0
info:
  title: API Argent-Bank
  description: >-
    API pour gérer les transactions bancaires d'un utilisateur, incluant la
    possibilité de visualiser, ajouter, modifier des informations sur les
    transactions.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Serveur de développement local
paths:
  /api/transactions/month:
    get:
      summary: >-
        Visualisation des transactions pour le mois en cours, groupées par
        compte
      description: >-
        Affiche toutes les transactions pour le mois en cours, groupées par
        compte.
      parameters:
        - name: account_id
          in: query
          description: L'identifiant du compte.
          required: true
          schema:
            type: string
        - name: month
          in: query
          description: Le mois pour lequel les transactions doivent être récupérées.
          required: true
          schema:
            type: string
            default: current_month
        - name: Authorization
          in: header
          description: Le token d'authentification
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        account_id:
                          type: string
                        account_name:
                          type: string
                        transactions:
                          type: array
                          items:
                            type: object
                            properties:
                              transaction_id:
                                type: string
                              amount:
                                type: number
                                format: float
                              type:
                                type: string
                                enum:
                                  - income
                                  - expense
                              date:
                                type: string
                                format: date
                              description:
                                type: string
                              categories:
                                type: array
                                items:
                                  type: string
                              note:
                                type: string
                              balance:
                                type: number
                                format: float
                  message:
                    type: string
                    example: Transactions successfully fetched.
        '400':
          description: Mauvaise requête (paramètres manquants ou incorrects)
        '401':
          description: Non autorisé (token manquant ou invalide)
        '404':
          description: Ressource non trouvée
  /api/transactions/{transaction_id}:
    get:
      summary: Visualisation des détails d'une transaction spécifique
      description: Affiche les détails d'une transaction spécifique.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
        - name: Authorization
          in: header
          description: Le token d'authentification
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      amount:
                        type: number
                        format: float
                      type:
                        type: string
                        enum:
                          - income
                          - expense
                      date:
                        type: string
                        format: date
                      description:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
                      balance:
                        type: number
                        format: float
                  message:
                    type: string
                    example: Transaction details successfully fetched.
        '400':
          description: Mauvaise requête (transaction_id incorrect)
        '401':
          description: Non autorisé (token manquant ou invalide)
        '404':
          description: Transaction non trouvée
  /api/transactions/{transaction_id}/update:
    put:
      summary: Mise à jour d'une transaction existante
      description: Modifie une transaction existante en remplaçant les informations spécifiées.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
        - name: Authorization
          in: header
          description: Le token d'authentification
          required: true
          schema:
            type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
                enum:
                  - income
                  - expense
              categories:
                type: array
                items:
                  type: string
              note:
                type: string
    responses:
      '200':
        description: Transaction mise à jour avec succès
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Transaction information updated successfully.
                transaction:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                    type:
                      type: string
                    categories:
                      type: array
                      items:
                        type: string
                    note:
                      type: string
      '400':
        description: Mauvaise requête (paramètres manquants ou incorrects)
      '401':
        description: Non autorisé (token manquant ou invalide)
      '404':
        description: Transaction non trouvée
  /api/transactions/{transaction_id}/modify:
    put:
      summary: Mise à jour partielle des informations d'une transaction existante
      description: >-
        Modifie partiellement les informations d'une transaction existante,
        telles que le type, les catégories et la note.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
        - name: Authorization
          in: header
          description: Le token d'authentification
          required: true
          schema:
            type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
                enum:
                  - income
                  - expense
              categories:
                type: array
                items:
                  type: string
              note:
                type: string
    responses:
      '200':
        description: Transaction partiellement mise à jour avec succès
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Transaction information updated successfully.
                transaction:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                    type:
                      type: string
                    categories:
                      type: array
                      items:
                        type: string
                    note:
                      type: string
      '400':
        description: Mauvaise requête (paramètres manquants ou incorrects)
      '401':
        description: Non autorisé (token manquant ou invalide)
      '404':
        description: Transaction non trouvée
  /api/transactions/{transaction_id}/delete_info:
    delete:
      summary: Suppression d'informations spécifiques d'une transaction
      description: >-
        Supprime certaines informations spécifiques d'une transaction, comme
        les catégories ou la note, sans supprimer la transaction elle-même.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
        - name: Authorization
          in: header
          description: Le token d'authentification
          required: true
          schema:
            type: string
        - name: categories
          in: query
          description: Liste des catégories à supprimer.
          schema:
            type: array
            items:
              type: string
        - name: note
          in: query
          description: La note à supprimer.
          schema:
            type: string
      responses:
        '200':
          description: Informations supprimées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transaction information deleted successfully.
                  transaction:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
        '400':
          description: Mauvaise requête (paramètres manquants ou incorrects)
        '401':
          description: Non autorisé (token manquant ou invalide)
        '404':
          description: Transaction non trouvée
components:
  schemas:
    Transaction:
      type: object
      properties:
        transaction_id:
          type: string
        amount:
          type: number
          format: float
        type:
          type: string
          enum:
            - income
            - expense
        date:
          type: string
          format: date
        description:
          type: string
        categories:
          type: array
          items:
            type: string
        note:
          type: string
        balance:
          type: number
          format: float