openapi: 3.0.0
info:
  title: API de Gestion des Transactions Bancaires
  description: >-
    API pour gérer les transactions bancaires d'un utilisateur, incluant la
    possibilité de visualiser, ajouter, modifier des informations sur les
    transactions.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Serveur de développement local
paths:
  /api/transactions/month:
    get:
      summary: >-
        Visualisation des transactions pour le mois en cours, groupées par
        compte
      description: >-
        Affiche toutes les transactions pour le mois en cours, groupées par
        compte.
      parameters:
        - name: account_id
          in: query
          description: L'identifiant du compte.
          required: true
          schema:
            type: string
        - name: month
          in: query
          description: Le mois pour lequel les transactions doivent être récupérées.
          required: true
          schema:
            type: string
            default: current_month
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        account_id:
                          type: string
                        account_name:
                          type: string
                        transactions:
                          type: array
                          items:
                            type: object
                            properties:
                              transaction_id:
                                type: string
                              amount:
                                type: number
                                format: float
                              type:
                                type: string
                                enum:
                                  - income
                                  - expense
                              date:
                                type: string
                                format: date
                              description:
                                type: string
                              categories:
                                type: array
                                items:
                                  type: string
                              note:
                                type: string
                              balance:
                                type: number
                                format: float
                  message:
                    type: string
                    example: Transactions successfully fetched.
  /api/transactions/{transaction_id}:
    get:
      summary: Visualisation des détails d'une transaction spécifique
      description: Affiche les détails d'une transaction spécifique.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      amount:
                        type: number
                        format: float
                      type:
                        type: string
                        enum:
                          - income
                          - expense
                      date:
                        type: string
                        format: date
                      description:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
                      balance:
                        type: number
                        format: float
                  message:
                    type: string
                    example: Transaction details successfully fetched.
  /api/transactions/{transaction_id}/update:
    put:
      summary: Ajout d'informations supplémentaires à une transaction existante
      description: >-
        Ajoute des informations supplémentaires à une transaction existante,
        telles que le type, les catégories, et la note.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
        - name: type
          in: query
          required: true
          description: Le type de la transaction
          schema:
            type: string
            enum:
              - income
              - expense
        - name: categories
          in: query
          description: Les catégories associées à la transaction
          schema:
            type: array
            items:
              type: string
        - name: note
          in: query
          description: Note à ajouter à la transaction
          schema:
            type: string
      responses:
        '200':
          description: Informations ajoutées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transaction information updated successfully.
                  transaction:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      type:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
  /api/transactions/{transaction_id}/modify:
    patch:
      summary: Modification des informations d'une transaction existante
      description: >-
        Modifie les informations d'une transaction existante, telles que le
        type, les catégories et la note.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: L'identifiant de la transaction
          schema:
            type: string
        - name: type
          in: query
          description: Le type de la transaction
          schema:
            type: string
            enum:
              - income
              - expense
        - name: categories
          in: query
          description: Les catégories associées à la transaction
          schema:
            type: array
            items:
              type: string
        - name: note
          in: query
          description: Note à modifier pour la transaction
          schema:
            type: string
      responses:
        '200':
          description: Informations modifiées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Transaction information modified successfully.
                  transaction:
                    type: object
                    properties:
                      transaction_id:
                        type: string
                      type:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      note:
                        type: string
components:
  schemas:
    Transaction:
      type: object
      properties:
        transaction_id:
          type: string
        amount:
          type: number
          format: float
        type:
          type: string
          enum:
            - income
            - expense
        date:
          type: string
          format: date
        description:
          type: string
        categories:
          type: array
          items:
            type: string
        note:
          type: string
        balance:
          type: number
          format: float
