openapi: 3.0.0
info:
  title: API Transactions
  description: API pour gérer les transactions des utilisateurs. Permet de visualiser les transactions par compte, afficher les détails d'une transaction, ainsi que modifier ou supprimer des informations sur une transaction.
  version: 1.0.0
  contact:
    name: Support Technique
    email: support@example.com
    url: https://example.com

paths:
  /transactions/current-month:
    get:
      summary: Récupérer les transactions du mois en cours
      description: Permet de visualiser toutes les transactions d'un utilisateur pour le mois en cours, groupées par compte.
      operationId: getTransactionsForCurrentMonth
      tags:
        - Transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Token d'authentification Bearer
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        accountId:
                          type: string
                          description: Identifiant du compte
                        transactions:
                          type: array
                          items:
                            type: object
                            properties:
                              transactionId:
                                type: string
                                description: Identifiant unique de la transaction
                              amount:
                                type: number
                                format: float
                                description: Montant de la transaction
                              description:
                                type: string
                                description: Description de la transaction
                              date:
                                type: string
                                format: date
                                description: Date de la transaction
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

  /transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction
      description: Permet de visualiser les détails d'une transaction spécifique.
      operationId: getTransactionDetails
      tags:
        - Transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Token d'authentification Bearer
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: Identifiant unique de la transaction
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  accountId:
                    type: string
                  amount:
                    type: number
                    format: float
                  description:
                    type: string
                  date:
                    type: string
                    format: date
        '404':
          description: Transaction non trouvée
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

    put:
      summary: Modifier les informations d'une transaction
      description: Permet de mettre à jour les informations d'une transaction spécifique.
      operationId: updateTransaction
      tags:
        - Transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Token d'authentification Bearer
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: Identifiant unique de la transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
                  description: Nouveau montant de la transaction
                description:
                  type: string
                  description: Nouvelle description de la transaction
                date:
                  type: string
                  format: date
                  description: Nouvelle date de la transaction
      responses:
        '200':
          description: Transaction mise à jour avec succès
        '400':
          description: Données invalides
        '404':
          description: Transaction non trouvée
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

    delete:
      summary: Supprimer une transaction
      description: Permet de supprimer une transaction spécifique.
      operationId: deleteTransaction
      tags:
        - Transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Token d'authentification Bearer
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: Identifiant unique de la transaction
      responses:
        '204':
          description: Transaction supprimée avec succès
        '404':
          description: Transaction non trouvée
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

  /transactions:
    post:
      summary: Ajouter une nouvelle transaction
      description: Permet d'ajouter une transaction à un compte existant.
      operationId: addTransaction
      tags:
        - Transactions
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Token d'authentification Bearer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
                  description: Identifiant du compte
                amount:
                  type: number
                  format: float
                  description: Montant de la transaction
                description:
                  type: string
                  description: Description de la transaction
                date:
                  type: string
                  format: date
                  description: Date de la transaction
      responses:
        '201':
          description: Transaction ajoutée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  accountId:
                    type: string
                  amount:
                    type: number
                    format: float
                  description:
                    type: string
                  date:
                    type: string
                    format: date
        '400':
          description: Données invalides
        '401':
          description: Non autorisé
        '500':
          description: Erreur serveur

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  security:
    - BearerAuth: []
